### ISSUE TITLE
[FER]Could the alpha/transparent value be adjustable ?

### ISSUE THREAD

**Issue by yw662** [zhanghai/gnome-shell-extension-transparent-top-bar#15] opened 2021-04-29 07:56 UTC
This extension set alpha value to 0.35 by defult, and there seems no way to change it without modifying the style sheet.

Maybe this is a design limitation of gnome, but could there be an option to adjust the alpha value ?

**Comment by yw662** [comment] 2021-04-29 08:16
From gnome's document it seems possible for an extension to have preferences, by adding a gsettings schema.
To apply the preference, it can be either like modifying the style sheet, or apply the style directly, instead of the style sheet, or it could be a CSS custom property (variable) if supported.

I am new to gnome extension but I would still like to help if this FER is approved.

**Comment by zhanghai** [comment] 2021-04-29 08:55
Duplicate of #1.

**Closed by zhanghai** 2021-04-29 08:55 UTC
